### ISSUE TITLE
Title and Favicon

### ISSUE THREAD

**Issue by Zemerik** [S-PScripts/chromebook-utilities#12]
Hey, for some reason your website's title is `Google Drive` and the favicon is a logo of Google drive. Why is that?

I suggest you change it to something else, maybe `Chromebook Utilities` or something like that. You may also want to use a logo or another favicon

Regards, 
Zemerik

**Comment by S-PScripts** [comment]
it's just a cloak so teachers think it's a normal website

**Comment by Zemerik** [comment]
oh ok.
