### ISSUE TITLE
About nvd123s tools

### ISSUE THREAD

**Issue by WatchGamingVideos** [S-PScripts/chromebook-utilities#17]
So is there a way u could get others to make links?

can close if no

**Comment by S-PScripts** [comment]
no i don't think so.

i think you probably made a mistake in your code at some point. i recommend trying to fork the interstellar repo again and redoing every change you've done until right before the point when links stopped working

**Comment by WatchGamingVideos** [comment]
oh where. I use my own code, and some code from Interstellar. Can you look through commits and find where it is messed up. Because I wouldn't know where that happened
