### ISSUE TITLE
update list of selenite games

### ISSUE THREAD

**Issue by skysthelimitt** [S-PScripts/chromebook-utilities#6]

**Comment by S-PScripts** [comment]
What links though?

**Comment by skysthelimitt** [comment]
https://selenite.cc
https://selenite.pages.dev/
https://selenite.skysthelimit.dev/
https://selenite.is-a.dev/
https://all-about-science.onrender.com/
https://robotics-docs.onrender.com/
https://contact.deleesportsmedicine.com/
https://learn-at.undo.it/
https://fediverse.faefox.org/
https://projects.blueshadows.cl/
https://contact.zverovich.net/

**Comment by S-PScripts** [comment]
You might want to make new onrender links, they don't work.

**Comment by skysthelimitt** [comment]
i should remove the onrender links, theyre gonna change a lot bc i hit bandwidth limits quickly
